<!Doctype html>
<html>
    <head>
        <title>Projet de demo D19.1</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous" />
    </head>
    <body>
        <div class="container">
            <?= $content ?>
        </div>
    </body>
</html>
